export const FETCH_BLOCKS_START = "FETCH_BLOCKS_START"
export const FETCH_BLOCKS_SUCCESS = "FETCH_BLOCKS_SUCCESS"
export const FETCH_BLOCKS_FAILURE = "FETCH_BLOCKS_FAILURE"

export const CHANGE_STOPS = "CHANGE_STOPS"